name: Build and Deploy

on:
  push:
    branches: [main, dev]

env:
  DOTNET_VERSION: "6.0.x"
  APP_NAME: "wolverine-gh"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - name: Install dependencies
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: |
          dotnet restore
          dotnet build -c Release --no-restore
          dotnet test
          dotnet publish -c Release --no-restore -o ./out

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: webapp
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: webapp
          path: ./out

      - name: Authenticate Az Cli
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          package: ./out
